* Personal emacs config

It's a work in progress, as any other configuration - mind you! :D
I'm also learning my way around elisp and creating packages.


* Inspired on the best out there :)

[[https://www.spacemacs.org/][Spacemacs]] is a great project, it's actually how I started using emacs, evil mode FTW.

Likewise, [[https://github.com/hlissner/doom-emacs][Doom Emacs]] is awesome and of course I've used it for some time.

Then over time I learned more about the Emacs ecosystem, started learning lispy languages,
tried out a couple of configurations and figured I like things in certain ways rather the others.

More than anything this is a good excercise for me which I slowly reap the benefits.

* Stuff TODO
  Couple of items I want to address, mostly ideas that I may or may not implement...

  + Better modularization
    + initialize layers based on a variable passed via command line
  + Understand and fix my font configuration
  + Have a better org-mode experience
  + Clean up 2nd-brain references
